version: '3.9'

services:
  frontend:
    restart: always
    build: ./app
    expose:
      - "8080"
    ports:
      - "8080:8080"
    command: yarn go
    volumes:
      - ./app:/home/app
  backend:
    restart: always
    build: ./server
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: yarn go
    volumes:
      - ./server:/usr/src/server
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d

volumes:
  app:
  server:
  nginx:
